/** Human labels for CompressReport.imagesSkipped reasons (see "What gets recompressed" in the README). */
export const SKIP_REASONS: Record<string, string> = {
  small: 'below the size threshold (20 KB)',
  noGain: 'would not get at least 10% smaller',
  softMask: 'transparency mask kept as is',
  matte: 'pre-blended transparency (/Matte)',
  imageMask: 'stencil mask',
  colorKeyMask: 'colour-key masked image',
  cmyk: 'CMYK colour',
  indexed: 'indexed (palette) colour',
  separation: 'spot colour (Separation)',
  deviceN: 'multi-ink colour (DeviceN)',
  lab: 'Lab colour',
  colorSpace: 'unsupported colour space',
  noColorSpace: 'no colour space',
  jpx: 'JPEG 2000 (browsers cannot decode it)',
  jbig2: 'JBIG2 (black-and-white scan)',
  ccitt: 'CCITT fax (black-and-white scan)',
  filter: 'unsupported compression',
  bitsPerComponent: 'not 8 bits per sample',
  decode: 'custom /Decode array',
  predictor: 'unsupported predictor',
  jpegTransform: 'Adobe or RGB-transform JPEG',
  jpegUnsupported: 'arithmetic, lossless or 12-bit JPEG',
  jpegMismatch: 'JPEG does not match its dictionary',
  jpegInvalid: 'invalid JPEG data',
  external: 'stored in an external file',
  malformed: 'malformed image dictionary',
  tooLarge: 'too large to decode',
  decodeError: 'damaged image data',
  codecDeclined: 'the browser codec declined it',
  codecError: 'the browser could not decode it',
  codecOutputInvalid: 'the browser produced an unusable JPEG',
};

export const skipLabel = (reason: string): string => SKIP_REASONS[reason] ?? reason;
