/**
 * Response headers for the site, written to dist/_headers in Cloudflare Pages' format
 * (https://developers.cloudflare.com/pages/configuration/headers/), plus a parser and matcher
 * implementing the same rules, so the dev server and the tests serve exactly what Pages will.
 *
 * Every response is cross-origin isolated (COOP + COEP), so the app runs in a process of its own
 * with full-resolution timers. The site loads nothing from other origins, so that costs nothing. The Content-Security-Policy also keeps it that way: no third-party
 * scripts, styles, fonts, images or connections.
 */

export const CONTENT_SECURITY_POLICY = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self'",
  "img-src 'self' data: blob:",
  "font-src 'self'",
  "connect-src 'self' blob:",
  "worker-src 'self'",
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
].join('; ');

export const HEADERS_FILE = `# Cloudflare Pages response headers. Generated by site/build.ts from site/src/headers.ts.
# https://developers.cloudflare.com/pages/configuration/headers/

/*
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Embedder-Policy: require-corp
  Cross-Origin-Resource-Policy: same-origin
  Content-Security-Policy: ${CONTENT_SECURITY_POLICY}
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()

# Content-hashed file names: cache forever.
/assets/*
  Cache-Control: public, max-age=31536000, immutable
`;

export interface HeaderRule {
  pattern: string;
  matcher: RegExp;
  set: [string, string][];
  detach: string[];
}

function toRegExp(pattern: string): RegExp {
  // Only the path matters locally; drop a scheme and host if the rule has one.
  const path = pattern.replace(/^https?:\/\/[^/]+/, '');
  let src = '';
  for (const part of path.split(/(\*|:[A-Za-z]\w*)/)) {
    if (part === '*') src += '(.*)';
    else if (part.startsWith(':') && part.length > 1) src += '([^/]+)';
    else src += part.replace(/[.+?^${}()|[\]\\]/g, '\\$&');
  }
  return new RegExp(`^${src}$`);
}

export function parseHeaders(text: string): HeaderRule[] {
  const rules: HeaderRule[] = [];
  let rule: HeaderRule | undefined;
  for (const raw of text.split(/\r?\n/)) {
    if (!raw.trim() || raw.trim().startsWith('#')) continue;
    if (!/^\s/.test(raw)) {
      rule = { pattern: raw.trim(), matcher: toRegExp(raw.trim()), set: [], detach: [] };
      rules.push(rule);
      continue;
    }
    if (!rule) throw new Error(`_headers: header without a URL pattern: ${raw}`);
    const line = raw.trim();
    if (line.startsWith('!')) {
      rule.detach.push(line.slice(1).trim().toLowerCase());
      continue;
    }
    const colon = line.indexOf(':');
    if (colon <= 0) throw new Error(`_headers: malformed header line: ${raw}`);
    rule.set.push([line.slice(0, colon).trim(), line.slice(colon + 1).trim()]);
  }
  return rules;
}

/**
 * Headers for a request path. As on Pages, every matching rule applies, a header set by more
 * than one rule gets its values joined with ", ", and `! Name` removes a header.
 */
export function headersFor(rules: HeaderRule[], pathname: string): Headers {
  const values = new Map<string, { name: string; values: string[] }>();
  const detached = new Set<string>();
  for (const r of rules) {
    if (!r.matcher.test(pathname)) continue;
    for (const [name, value] of r.set) {
      const key = name.toLowerCase();
      const entry = values.get(key) ?? { name, values: [] };
      entry.values.push(value);
      values.set(key, entry);
    }
    for (const d of r.detach) detached.add(d);
  }
  const h = new Headers();
  for (const [key, { name, values: v }] of values) if (!detached.has(key)) h.set(name, v.join(', '));
  return h;
}
